springdoc:
  api-docs:
    enabled: true
    path: /docs/api-docs
  swagger-ui:
    path: /docs/swagger.html

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}

mercadopago:
  access:
    token: ${MERCADOPAGO_ACCESSTOKEN}

logging:
  file:
    path: ${LOG_PATH}
  pattern:
    dateformat: "dd/MM/yyyy HH:mm:ss.SSS"

management:
  endpoints:
    web:
      exposure:
        include: health,metrics
      base-path: /v1/actuator
  otlp:
    metrics:
      export:
        url: ${METRICS_ENDPOINT:http://0.0.0.0:4318/v1/metrics}
        step: 30s
    tracing:
      endpoint: ${TRACING_ENDPOINT:http://0.0.0.0:4318/v1/traces}
    log:
      endpoint: ${LOGGING_ENDPOINT:http://0.0.0.0:4317}
  tracing:
    sampling:
      probability: 1.0
  metrics:
    tags:
      department: ${SERVICE_DEPARTMENT:software}
      service: ${spring.application.name}
      env: ${SERVICE_ENV:${ENV_NAME}}
      region: ${SERVICE_REGION:brazil-south}
      instance.id: ${SERVICE_INSTANCE_ID:default}

spring:
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  threads:
    virtual:
      enabled: true
  lifecycle:
    timeout-per-shutdown-phase: "10s"
  jackson:
    date-format: dd/MM/yyyy HH:mm:ss
    time-zone: America/Sao_Paulo
    locale: br
  jpa:
    open-in-view: false
  datasource:
    hikari:
      maxLifetime: '2000000'
      poolName: SpringBootHikariCP
      connectionTimeout: '30000'
      idleTimeout: '30000'
      minimumIdle: '5'
      maximumPoolSize: '20'
      schema: public
    url: ${DATASOURCE_URL}
    type: com.zaxxer.hikari.HikariDataSource
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  application:
    name: yoop-api

server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false
  port: 8091
  shutdown: graceful
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

fe-ticket-check-url: ${FRONTEND_TICKET_CHECK_URL}
upload-dir: ${UPLOAD_PATH}
