services:
  db:
    container_name: psql-db
    image: postgres:16.4
    environment:
      - POSTGRES_DB=ifspcbt
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - TZ=America/Sao_Paulo
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - ifspcbt
    restart: always

  backend:
    container_name: tickets-api
    image: ghcr.io/ifspcbt-devspace/ifspcbt-devspace/tickets-ifsp-api:latest
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - TZ=America/Sao_Paulo
      - JWT_SECRET_KEY=secret
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USERNAME=example@gmail.com
      - MAIL_PASSWORD=password
      - DATASOURCE_URL=jdbc:postgresql://psql-db:5432/ifspcbt
      - DATASOURCE_USERNAME=root
      - DATASOURCE_PASSWORD=password
      - ENCRYPTOR_VALUE=secret
      - FRONTEND_TICKET_CHECK_URL=https://eventos.ifspcbt.shop/admin/ticket/%s/check
      - MERCADOPAGO_ACCESSTOKEN=token
      - MERCADOPAGO_WEBHOOK_SECRET=secret
      - ENV_NAME=prod
      - LOG_PATH=/ticketsapi/logs/
      - UPLOAD_PATH=/ticketsapi/uploads/
      - METRICS_ENDPOINT=http://otlp:4318/v1/metrics
      - TRACING_ENDPOINT=http://otlp:4318/v1/traces
      - LOGGING_ENDPOINT=http://otlp:4317
      - SERVICE_DEPARTMENT=software
      - SERVICE_ENV=prod
      - SERVICE_REGION=brazil-south
      - SERVICE_INSTANCE_ID=default
    volumes:
      - /home/ticketsapi/uploads:/ticketsapi/uploads
      - /home/ticketsapi/logs:/ticketsapi/logs
    ports:
      - "8091:8091"
    depends_on:
      - db
    networks:
      - ifspcbt

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 60 --label-enable

volumes:
  db_data:

networks:
  ifspcbt:
    driver: bridge
    external: true
