services:
  otel-collector:
    container_name: otlp
    image: otel/opentelemetry-collector-contrib:0.123.0
    restart: always
    networks:
      - ifspcbt
    command:
      - --config=/etc/otelcol-contrib/otel-collector.yml
    volumes:
      - ./docker/collector/otel-collector.yml:/etc/otelcol-contrib/otel-collector.yml
    expose:
      - "4317"
    ports:
      - "1888" # pprof extension
      - "8888" # Prometheus metrics exposed by the Collector
      - "8889" # Prometheus exporter metrics
      - "13133" # health_check extension
      - "4317" # OTLP gRPC receiver
      - "4318" # OTLP http receiver
      - "55679" # zpages extension
    depends_on:
      - loki
      - tempo
      - prometheus

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: always
    user: root
    networks:
      - ifspcbt
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-remote-write-receiver
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus-data:/prometheus
    ports:
      - "9090"

  loki:
    container_name: loki
    image: grafana/loki:latest
    volumes:
      - ./docker/loki/loki-config.yml:/etc/loki/config.yaml
      - ./loki-data/chunks:/loki/chunks
      - ./loki-data/index:/loki/index
      - ./loki-data/cache:/loki/cache
      - ./loki-data/compactor:/loki/compactor
    environment:
      - LOKI_STORAGE_CONFIG_FILE=/etc/loki/config.yaml
    restart: always
    networks:
      - ifspcbt
    ports:
      - "3100"

  init:
    image: &tempoImage grafana/tempo:latest
    user: root
    networks:
      - ifspcbt
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/var/tempo"
    volumes:
      - ./tempo-data:/var/tempo

  tempo:
    container_name: tempo
    image: *tempoImage
    command: [ "-config.file=/etc/tempo.yml" ]
    restart: always
    networks:
      - ifspcbt
    volumes:
      - ./docker/tempo/tempo.yml:/etc/tempo.yml
      - ./tempo-data:/var/tempo
    ports:
      - "3200" # tempo
      - "4317" # otlp grpc
      - "4318" # otlp http
    depends_on:
      - init

  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: always
    user: root
    networks:
      - ifspcbt
    volumes:
      - ./docker/grafana/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3001:3000"

networks:
  ifspcbt:
    driver: bridge
    external: true