auth_enabled: false

server:
  # API HTTP interna (UI e endpoints do Tempo)
  http_listen_address: 0.0.0.0
  http_listen_port: 3200
  # Servidor gRPC interno (não é o OTLP, mas usado pelo próprio Tempo)
  grpc_listen_address: 0.0.0.0
  grpc_listen_port: 9095

distributor:
  # Receptores de spans no Distribuidor
  receivers:
    otlp:
      protocols:
        # Habilita OTLP/gRPC na porta padrão 4317
        grpc:
          endpoint: 0.0.0.0:4317
        # Habilita OTLP/HTTP na porta padrão 4318
        http:
          endpoint: 0.0.0.0:4318

ingester:
  trace_idle_period: 10s
  max_block_duration: 5m

compactor:
  compaction:
    block_retention: 1h

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/traces